[package]
name = "script_bs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
ffi = "0.1.1"
glam = "0.30.0"
serde_json = "1.0.140"
wasmi = "0.41.0"
wat = "1.227.1"

[dev-dependencies]
wasmprinter = "0.227.1"
